# backend/finance_sync.py
import asyncio
import logging
import json
import aiofiles
import httpx
from datetime import datetime
from pathlib import Path
import sys

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))

from backend.database import get_all_settings, init_db
from backend.config import DOCS_PATH, STEWARD_FINANCE_FOLDER

logger = logging.getLogger(__name__)

async def run_finance_sync():
    """
    Fetches YNAB budget data and saves both a text summary and structured JSON.
    """
    logger.info("--- Running YNAB Finance Sync ---")
    
    try:
        await init_db()
        settings = await get_all_settings()
        
        token = settings.get("ynab_personal_token")
        finance_folder_name = settings.get("steward_finance_folder", STEWARD_FINANCE_FOLDER)
        
        if not token or token == "YOUR_YNAB_TOKEN":
            logger.warning("YNAB token not configured. Skipping.")
            return

        categories_json = settings.get("ynab_categories_to_track", "[]")
        try:
            categories_to_track = json.loads(categories_json)
            if not isinstance(categories_to_track, list): raise ValueError
        except:
            categories_to_track = []

        budget_id = "last-used"
        api_url = f"https://api.youneedabudget.com/v1/budgets/{budget_id}/categories"
        headers = {"Authorization": f"Bearer {token}"}
        
        summary_lines = []
        structured_data = []
        
        async with httpx.AsyncClient() as client:
            response = await client.get(api_url, headers=headers)
            response.raise_for_status()
            
            data = response.json()
            category_groups = data.get("data", {}).get("category_groups", [])
            
            for group in category_groups:
                for category in group.get("categories", []):
                    if category.get("name") in categories_to_track:
                        name = category["name"]
                        budgeted = category["budgeted"] / 1000.0
                        spent = abs(category["activity"] / 1000.0)
                        remaining = category["balance"] / 1000.0
                        
                        percent_spent = (spent / budgeted) * 100 if budgeted > 0 else 0
                        
                        summary_lines.append(
                            f"- {name}: ${spent:,.2f} spent of ${budgeted:,.2f}. (${remaining:,.2f} left). {percent_spent:.0f}% used."
                        )
                        
                        # === NEW: Structured Data for Frontend ===
                        structured_data.append({
                            "category": name,
                            "budgeted": budgeted,
                            "spent": spent,
                            "remaining": remaining,
                            "percent": round(percent_spent, 1)
                        })

        summary = "\n".join(summary_lines) if summary_lines else "No tracked categories found."
            
        output_path = DOCS_PATH / finance_folder_name
        output_path.mkdir(parents=True, exist_ok=True)
        output_file = output_path / "ynab_summary.json"
        
        output_data = {
            "last_updated": datetime.now().isoformat(),
            "summary": summary,
            "structured": structured_data # <--- Saved here
        }
        
        async with aiofiles.open(output_file, "w") as f:
            await f.write(json.dumps(output_data, indent=2))
            
        logger.info(f"✅ YNAB finance data saved.")

    except Exception as e:
        logger.error(f"FAILED to run YNAB finance sync: {e}", exc_info=True)

async def get_finance_structured(settings):
    """
    Reads the structured finance data from the JSON file generated by run_finance_sync.
    """
    try:
        folder = settings.get("steward_finance_folder", STEWARD_FINANCE_FOLDER)
        path = DOCS_PATH / folder / "ynab_summary.json"
        
        if path.exists():
            async with aiofiles.open(path, "r") as f:
                content = await f.read()
                data = json.loads(content)
                return data.get("structured", [])
    except Exception as e:
        logger.error(f"Error reading finance structured data: {e}")
    
    return []

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(run_finance_sync())